<?xml version="1.0" encoding="utf-8"?><Database Name="DoAn" Class="bookDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-EBUN5JD\TIEN;Initial Catalog=DoAn;Integrated Security=True" SettingsObjectName="LibrarySys.Properties.Settings" SettingsPropertyName="DoAnConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_sach" Member="tbl_saches">
    <Type Name="tbl_sach">
      <Column Name="ISBN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Tittle" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Author" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Manufacturer" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>